language: generic
# We need super user permissions to execute this build
sudo: required

# We need the docker cli pre-installed
services:
  - docker

# Commands to execute before tests are run
before_install:
  - docker build -t fxsheikh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fxsheikh/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env:  "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-126102699696"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
