language: generic
# We need super user permissions to execute this build
sudo: required

# We need the docker cli pre-installed
services:
  - docker

# Commands to execute before tests are run
before_install:
  - docker build -t fxsheikh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fxsheikh/docker-react npm run test
