version: '3'
services:
  web:
    stdin_open: true
    build:
      # Where we want files and folders for this image to be pulled fro
      context: .
      dockerfile: Dockerfile.dev
    ports:
      # map port 3000 outside container to port 3000 inside container
      - "3000:3000"
    volumes:
      - /app/node_modules
      # map this folder outside container to app folder inside container
      - .:/app
  tests:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]